### ISSUE TITLE
NetworkPolicy prevents update job to access kubernetes api server

### ISSUE THREAD

**Issue by christian-ftapi** [GDATASoftwareAG/gdscan#13]
Dear Sir or Madam,

we have problems regarding the update cronjob. Basically the ceated Pod is unable to communicate with our Kubernetes API Server and all pods contain the following logs:

```
E0210 11:00:33.465950       1 memcache.go:238] couldn't get current server API group list: Get "https://10.240.16.1:443/api?timeout=32s": dial tcp 10.240.16.1:443: i/o timeout
E0210 11:01:03.470320       1 memcache.go:238] couldn't get current server API group list: Get "https://10.240.16.1:443/api?timeout=32s": dial tcp 10.240.16.1:443: i/o timeout
E0210 11:01:33.474188       1 memcache.go:238] couldn't get current server API group list: Get "https://10.240.16.1:443/api?timeout=32s": dial tcp 10.240.16.1:443: i/o timeout
E0210 11:02:03.475295       1 memcache.go:238] couldn't get current server API group list: Get "https://10.240.16.1:443/api?timeout=32s": dial tcp 10.240.16.1:443: i/o timeout
Unable to connect to the server: dial tcp 10.240.16.1:443: i/o timeout
```

Ich checked the related [manifests](https://github.com/GDATASoftwareAG/gdscan/blob/main/charts/gdscan/templates/update.yaml) and found that you add an NetworkPolicy which applies to the CronJob and only allows communication with the Port 6443. However the Port of our Kubernetes-API Server is different (e.g. 30231).

Since it is not guaranteed that an API-Server has the Port 6443 I would either recommend to make that Port configurable or to completely drop the NetworkPolicy.

For the time being, I think that disabling the HelmRelease and changing the Port by hand is the best I can do.

If you have any questions please don't hesitate to ask. :) 

Kind regards,
Christian Weber

**Comment by unglaublicherdude** [comment]
Hey, a PR is open here: https://github.com/GDATASoftwareAG/gdscan/pull/14

we made it not optional (default is true) to deploy the NetworkPolicy. This is somewhat like in the bitnami charts. When this is merged you can either configure the port that fits for you or deactivate the default Policy and deploy your own (this is also the way to go when you use something like cilium which has its own NetworkPolicy format) into the namespace.
