### ISSUE TITLE
Chart broken since 1.4.0

### ISSUE THREAD

**Issue by mwipplinger-ftapi** [GDATASoftwareAG/gdscan#31]
The `deployment` template references a volumeMount that never gets defined in the `volumes:` section of the deployment.
Helm/K8s rightfully rejects the patch to enact this change as it's not a valid deployment configuration.

Here a short log:
```
Helm upgrade failed: cannot patch "gdscan" with kind Deployment: Deployment.apps "gdscan" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "server-var-log"
```

**Comment by lennartdohmann** [comment]
Analysis:
* StafefulSet works
* Deployment was broken due to missing volume

Fixed in gdscan-1.5.0
