### ISSUE TITLE
Pods are not compatible with PodSecurityAdmission level "restricted"

### ISSUE THREAD

**Issue by jdftapi** [GDATASoftwareAG/gdscan#36]
We are trying to deploy this chart in a namespace using PodSecurityAdmission level `restricted`.

The pods spawned by this helm chart violate the PSA with their default `podSecurityContext` and `containerSecurityContext`.
We also cannot change the securityContext values for all containers / pods, making the helm chart incompatible.

Please either make the default `podSecurityContext` and `containerSecurityContext` of all pods and containers compatible with PSA level `restricted` or at least allow us to override all `SecurityContexts` of all containers and pods.

**Comment by pstadermann** [comment]
Containers are compatible with PodSecurityAdmission level "restricted" in 1.6.0.
