### ISSUE TITLE
Pod Security context is missing in Server Container

### ISSUE THREAD

**Issue by azteckiesel** [GDATASoftwareAG/gdscan#39]
Hello Philip,

we faced issues while deploy the new GD version 1.5.1 (and before) on our infra.
This got resolved with adding below command after line 55 in deployment.yaml:
          _{{- if .Values.server.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.server.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}_

Bye
Christian

**Comment by pstadermann** [comment]
Containers are compatible with PodSecurityAdmission level "restricted" in 1.6.0.
