### ISSUE TITLE
Allow the "scan-socket" volume to be moved into memory and/or persistent volume storage

### ISSUE THREAD

**Issue by jdftapi** [GDATASoftwareAG/gdscan#49]
When running GDScan on a k8s node with suboptimal HDD storage performance, be it through storage type or through neighbouring pods, the performance of the scanner can be degraded by the HDD bottleneck due to the fact that the scan socket always resides on the node.

It would be great to have the possibility of putting the scan socket volume into Memory or onto a custom disk using a persistent volume claim.

**Comment by oOoHoCo** [comment]
Hello there,

wouldn't it be a bit better to have the possibility to even move thos mounts to PVCs because if you have it in memory and want to scan large files (e.g. a zip file that contains logs ... will be huge when decompressed) the memory could pose a limit that you do not want.

Regards,

Ben

**Comment by jdftapi** [comment]
It would be great to have both possibilities, as the performance of the storage can be limited even on PVCs, depending on the environment.

For most use cases, PVC should be preferable, I agree.
